### ISSUE TITLE
Error in launching agent in Ubuntu 22.04

### ISSUE THREAD

**Issue by KarthiAru** [supervisely/agent#86]
Hi,

I'm getting the below error while launching the agent in Ubuntu 22.04. It appears to be due to a malformed URL.

```
 ~  bash <(curl -fsSLg "https://app.supervisely.com/api/agent/k7esGwGwG7QADgxfynbZN5OMkUkmJR5s?agentImage=supervisely/agent:6.8.33")
Pulling agent and net-client docker images...
6.8.33: Pulling from supervisely/agent
Digest: sha256:fb4181e0ec1d5038dd44b9c2bd1f15edc82ae4bd946ba15fce7cbed49875bb5f
Status: Image is up to date for supervisely/agent:6.8.33
docker.io/supervisely/agent:6.8.33

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview supervisely/agent:6.8.33
latest: Pulling from supervisely/sly-net-client
Digest: sha256:2794c0281f5937fb3c77efcd32d5845db67c5ad67259aef4f49c1c67251d38e0
Status: Image is up to date for supervisely/sly-net-client:latest
docker.io/supervisely/sly-net-client:latest

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview supervisely/sly-net-client:latest
Remove existing container if any...
a7c44407d62e
5b762558f2783b90af84cd4761c809add87d4635d2abd5fcd1fbfe541e1ff09c
supervisely-agent-k7esGwGw
============ You can close this terminal safely now ============
Debugger is disabled
{"message": "NVIDIA runtime is not enabled. Checking if it can be enabled...", "timestamp": "2024-08-19T06:22:05.886Z", "level": "debug"}
{"message": "NVIDIA runtime is available. Will restart Agent with NVIDIA runtime.", "timestamp": "2024-08-19T06:22:06.614Z", "level": "debug"}
{"message": "Agent is restarting due to options change", "envs_changes": {"SUPERVISELY_AGENT_FILES": "/opt/supervisely/agents/agent-files-k7esGwGw", "SLY_APPS_DOCKER_REGISTRY": null, "DELETE_TASK_DIR_ON_FAILURE": "true", "DELETE_TASK_DIR_ON_FINISH": "true", "OFFLINE_MODE": false, "CPU_LIMIT": 0, "MEM_LIMIT": 0, "SECURITY_OPT": null, "HTTP_PROXY": "", "HTTPS_PROXY": "", "NO_PROXY": "", "NET_CLIENT_DOCKER_IMAGE": "supervisely/sly-net-client:latest", "NET_SERVER_PORT": 51822, "DOCKER_IMAGE": "supervisely/agent:6.8.33", "FORCE_CPU_ONLY": "false", "LOG_LEVEL": "debug", "AGENT_HOST_DIR": "~/.supervisely-agent"}, "volumes_changes": {"~/.supervisely-agent": {"bind": "/sly_agent", "mode": "rw"}, "/opt/supervisely/agents/agent-files-k7esGwGw": {"bind": "/app/sly-files", "mode": "rw"}}, "runtime_changes": {"runc": "nvidia"}, "ca_cert_changed": false, "timestamp": "2024-08-19T06:22:06.748Z", "level": "info"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.46/containers/create?name=supervisely-agent-k7esGwGw-1kRdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workdir/agent/main.py", line 287, in <module>
    init_envs()
  File "/workdir/agent/main.py", line 273, in init_envs
    agent_utils.restart_agent(
  File "/workdir/agent/worker/agent_utils.py", line 1020, in restart_agent
    container: Container = docker_api.containers.run(
  File "/usr/local/lib/python3.8/dist-packages/docker/models/containers.py", line 847, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.8/dist-packages/docker/models/containers.py", line 906, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.8/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.46/containers/create?name=supervisely-agent-k7esGwGw-1kRdf: Bad Request ("create ~/.supervisely-agent: "~/.supervisely-agent" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")

```

**Comment by KarthiAru** [comment]
I resolved the issue by updating "Agent host directory" to the absolute path "/home/<username>/.supervisely-agent" in the advanced settings.
